[sdl]
fullscreen=false
windowresolution=1280x800
output=opengl

[dosbox]
title=Gruniozerca SETUP
machine=svga_s3
memsize=16

[cpu]
cputype=486
cycles=fixed 50000

[dos]
ver=6.22
dpmi=true

[sblaster]
sbtype=sb16
sbbase=220
irq=5
dma=1
hdma=5

[speaker]
pcspeaker=true

[autoexec]
mount c "C:\Users\sebas\Documents\VSC\Grunio\gruniozerca\dos"
c:
mkdir temp
SET TEMP=C:\TEMP
SET TMP=C:\TEMP
SET CWSDPMI_SWAP=C:\TEMP\CWSDPMI.SWP
SET BLASTER=A220 I5 D1 H5 T6
build\SETUP.EXE
